export const authInitialState ={
    isAuthenticated:false,
    currentUser:{},
    user:"",
    password:"",
    email:"",
    fullName:"",
    profilePictureUrl:"",
    phoneNumber:"",
    ilanKisiFullName:"",
    ilanKisiTel:"",
    ilanKisiFoto:"",
    ilanKisiMail:"",


}

export const authReducer = (state, action) => {
    switch (action.type) {
        case"setAuthenticated":
            return{
                ...state,
                isAuthenticated:action.payload
            }
        case"currentUser":
            return{
                ...state,
                currentUser:action.payload
            }
        case"user":
            return{
                ...state,
                user:action.payload
            }
        case"password":
            return{
                ...state,
                password:action.payload
            }
        case"email":
            return{
                ...state,
                email:action.payload
            }
        case"fullName":
            return{
                ...state,
                fullName:action.payload
            }
        case"phoneNumber":
            return{
                ...state,
                phoneNumber:action.payload
            }
        case"profilePictureUrl":
            return{
                ...state,
                profilePictureUrl:action.payload
            }
        case"ilanKisiFullName":
            return{
                ...state,
                ilanKisiFullName:action.payload
            }
        case"ilanKisiTel":
            return{
                ...state,
                ilanKisiTel:action.payload
            }
        case"ilanKisiFoto":
            return{
                ...state,
                ilanKisiFoto:action.payload
            }
        case"ilanKisiMail":
            return{
                ...state,
                ilanKisiMail:action.payload
            }
        case"logOut":
            return{
                ...state,
                currentUser:"",
            }
        case"resetRegisterForm":
            return{
                ...state,
                user:"",
                password:"",
                email:"",
                fullName:"",
                profilePictureUrl:"",
                phoneNumber:""
            }
    }
};

